// <auto-generated />
namespace Encuesta.Infraestructura.Datos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EncuestaV1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EncuestaV1));
        
        string IMigrationMetadata.Id
        {
            get { return "201708240149454_EncuestaV1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
